title: Mazatech
description: 2D vector graphics engines company
google_analytics: UA-90357630-1
copyright: (C) 2005-2017 Mazatech, S.r.l.
vatid: VAT ID IT03498460405
rights: All rights reserved
exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md
sass:
  sass_dir: _includes
  #style: compressed
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]