# Site settings
title: "Mazatech, 2D vector graphics engines company"
description: "A software company focused on the development of innovative solutions for 2D vector graphics realtime rendering"
description2:
url: https://www.mazatech.com
enforce_ssl: www.mazatech.com

# Company settings
company_name: "MAZATECH"
company_name_ext: "Mazatech Srl"
company_vatid: "IT03498460405"
company_watchword: "2D vector graphics engines company"
company_email: "info@mazatech.com"
company_telephone: "+39 0547 57435"
company_country: "Italy"
company_city: "Longiano"
company_province: "FC"
company_postalcode: "47020"
company_street: "Via Rosario Livatino, 2"
company_founder_1_given_name: "Michele"
company_founder_1_family_name: "Fabbri"
company_founder_2_given_name: "Matteo"
company_founder_2_family_name: "Muratori"
company_founding_date: "2005-03-02"

facebook_username: "mazatechsrl"
twitter_username: "Mazatech1"
github_username: "Mazatech"

# Google-analytics
google-analytics:
  id: "UA-90357630-1"

exclude: ['package.json', 'src' , 'node_modules']
